# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f760feaf0dfbd4b197792de46d758e74bfb7cbb40fb6a75532c1c8a4f60cdeef2164748a4d4d0c4be126ed49fa7dd11b6465d981ae1395fcddf44803aa17807

test:
  secret_key_base: c66e4b5c7be59935530f60bcbe6bf94f4e01f3d4f00a555b49cb8196bb2620fc3031c53c6add96cab266bd5d9ce56dba2f1cb28059a909bf3e94025d1f68f008

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
